use chess::Move;


const MOVE_MAP: [Move; 1744] = [

    ///////////////////////////////////////////////
    ///////////////// ROOK MOVES //////////////////
    ///////////////////////////////////////////////

    Move::new(chess::Square::A1, chess::Square::A2),
    Move::new(chess::Square::A1, chess::Square::A3),
    Move::new(chess::Square::A1, chess::Square::A4),
    Move::new(chess::Square::A1, chess::Square::A5),
    Move::new(chess::Square::A1, chess::Square::A6),
    Move::new(chess::Square::A1, chess::Square::A7),
    Move::new(chess::Square::A1, chess::Square::A8),
    Move::new(chess::Square::A1, chess::Square::B1),
    Move::new(chess::Square::A1, chess::Square::C1),
    Move::new(chess::Square::A1, chess::Square::D1),
    Move::new(chess::Square::A1, chess::Square::E1),
    Move::new(chess::Square::A1, chess::Square::F1),
    Move::new(chess::Square::A1, chess::Square::G1),
    Move::new(chess::Square::A1, chess::Square::H1),

    Move::new(chess::Square::A2, chess::Square::A1),
    Move::new(chess::Square::A2, chess::Square::A3),
    Move::new(chess::Square::A2, chess::Square::A4),
    Move::new(chess::Square::A2, chess::Square::A5),
    Move::new(chess::Square::A2, chess::Square::A6),
    Move::new(chess::Square::A2, chess::Square::A7),
    Move::new(chess::Square::A2, chess::Square::A8),
    Move::new(chess::Square::A2, chess::Square::B2),
    Move::new(chess::Square::A2, chess::Square::C2),
    Move::new(chess::Square::A2, chess::Square::D2),
    Move::new(chess::Square::A2, chess::Square::E2),
    Move::new(chess::Square::A2, chess::Square::F2),
    Move::new(chess::Square::A2, chess::Square::G2),
    Move::new(chess::Square::A2, chess::Square::H2),

    Move::new(chess::Square::A3, chess::Square::A1),
    Move::new(chess::Square::A3, chess::Square::A2),
    Move::new(chess::Square::A3, chess::Square::A4),
    Move::new(chess::Square::A3, chess::Square::A5),
    Move::new(chess::Square::A3, chess::Square::A6),
    Move::new(chess::Square::A3, chess::Square::A7),
    Move::new(chess::Square::A3, chess::Square::A8),
    Move::new(chess::Square::A3, chess::Square::B3),
    Move::new(chess::Square::A3, chess::Square::C3),
    Move::new(chess::Square::A3, chess::Square::D3),
    Move::new(chess::Square::A3, chess::Square::E3),
    Move::new(chess::Square::A3, chess::Square::F3),
    Move::new(chess::Square::A3, chess::Square::G3),
    Move::new(chess::Square::A3, chess::Square::H3),

    Move::new(chess::Square::A4, chess::Square::A1),
    Move::new(chess::Square::A4, chess::Square::A2),
    Move::new(chess::Square::A4, chess::Square::A3),
    Move::new(chess::Square::A4, chess::Square::A5),
    Move::new(chess::Square::A4, chess::Square::A6),
    Move::new(chess::Square::A4, chess::Square::A7),
    Move::new(chess::Square::A4, chess::Square::A8),
    Move::new(chess::Square::A4, chess::Square::B4),
    Move::new(chess::Square::A4, chess::Square::C4),
    Move::new(chess::Square::A4, chess::Square::D4),
    Move::new(chess::Square::A4, chess::Square::E4),
    Move::new(chess::Square::A4, chess::Square::F4),
    Move::new(chess::Square::A4, chess::Square::G4),
    Move::new(chess::Square::A4, chess::Square::H4),

    Move::new(chess::Square::A5, chess::Square::A1),
    Move::new(chess::Square::A5, chess::Square::A2),
    Move::new(chess::Square::A5, chess::Square::A3),
    Move::new(chess::Square::A5, chess::Square::A4),
    Move::new(chess::Square::A5, chess::Square::A6),
    Move::new(chess::Square::A5, chess::Square::A7),
    Move::new(chess::Square::A5, chess::Square::A8),
    Move::new(chess::Square::A5, chess::Square::B5),
    Move::new(chess::Square::A5, chess::Square::C5),
    Move::new(chess::Square::A5, chess::Square::D5),
    Move::new(chess::Square::A5, chess::Square::E5),
    Move::new(chess::Square::A5, chess::Square::F5),
    Move::new(chess::Square::A5, chess::Square::G5),
    Move::new(chess::Square::A5, chess::Square::H5),

    Move::new(chess::Square::A6, chess::Square::A1),
    Move::new(chess::Square::A6, chess::Square::A2),
    Move::new(chess::Square::A6, chess::Square::A3),
    Move::new(chess::Square::A6, chess::Square::A4),
    Move::new(chess::Square::A6, chess::Square::A5),
    Move::new(chess::Square::A6, chess::Square::A7),
    Move::new(chess::Square::A6, chess::Square::A8),
    Move::new(chess::Square::A6, chess::Square::B6),
    Move::new(chess::Square::A6, chess::Square::C6),
    Move::new(chess::Square::A6, chess::Square::D6),
    Move::new(chess::Square::A6, chess::Square::E6),
    Move::new(chess::Square::A6, chess::Square::F6),
    Move::new(chess::Square::A6, chess::Square::G6),
    Move::new(chess::Square::A6, chess::Square::H6),

    Move::new(chess::Square::A7, chess::Square::A1),
    Move::new(chess::Square::A7, chess::Square::A2),
    Move::new(chess::Square::A7, chess::Square::A3),
    Move::new(chess::Square::A7, chess::Square::A4),
    Move::new(chess::Square::A7, chess::Square::A5),
    Move::new(chess::Square::A7, chess::Square::A6),
    Move::new(chess::Square::A7, chess::Square::A8),
    Move::new(chess::Square::A7, chess::Square::B7),
    Move::new(chess::Square::A7, chess::Square::C7),
    Move::new(chess::Square::A7, chess::Square::D7),
    Move::new(chess::Square::A7, chess::Square::E7),
        
    Move::new(chess::Square::A8, chess::Square::A1),
    Move::new(chess::Square::A8, chess::Square::A2),
    Move::new(chess::Square::A8, chess::Square::A3),
    Move::new(chess::Square::A8, chess::Square::A4),
    Move::new(chess::Square::A8, chess::Square::A5),
    Move::new(chess::Square::A8, chess::Square::A6),
    Move::new(chess::Square::A8, chess::Square::A7),
    Move::new(chess::Square::A8, chess::Square::B8),
    Move::new(chess::Square::A8, chess::Square::C8),
    Move::new(chess::Square::A8, chess::Square::D8),
    Move::new(chess::Square::A8, chess::Square::E8),
    Move::new(chess::Square::A8, chess::Square::F8),
    Move::new(chess::Square::A8, chess::Square::G8),

    ///////////////////////////////////////////////

    Move::new(chess::Square::B1, chess::Square::A2),
    Move::new(chess::Square::B1, chess::Square::A3),
    Move::new(chess::Square::B1, chess::Square::A4),
    Move::new(chess::Square::B1, chess::Square::A5),
    Move::new(chess::Square::B1, chess::Square::A6),
    Move::new(chess::Square::B1, chess::Square::A7),
    Move::new(chess::Square::B1, chess::Square::A8),
    Move::new(chess::Square::B1, chess::Square::B1),
    Move::new(chess::Square::B1, chess::Square::C1),
    Move::new(chess::Square::B1, chess::Square::D1),
    Move::new(chess::Square::B1, chess::Square::E1),
    Move::new(chess::Square::B1, chess::Square::F1),
    Move::new(chess::Square::B1, chess::Square::G1),
    Move::new(chess::Square::B1, chess::Square::H1),

    Move::new(chess::Square::B2, chess::Square::A1),
    Move::new(chess::Square::B2, chess::Square::A3),
    Move::new(chess::Square::B2, chess::Square::A4),
    Move::new(chess::Square::B2, chess::Square::A5),
    Move::new(chess::Square::B2, chess::Square::A6),
    Move::new(chess::Square::B2, chess::Square::A7),
    Move::new(chess::Square::B2, chess::Square::A8),
    Move::new(chess::Square::B2, chess::Square::B2),
    Move::new(chess::Square::B2, chess::Square::C2),
    Move::new(chess::Square::B2, chess::Square::D2),
    Move::new(chess::Square::B2, chess::Square::E2),
    Move::new(chess::Square::B2, chess::Square::F2),
    Move::new(chess::Square::B2, chess::Square::G2),
    Move::new(chess::Square::B2, chess::Square::H2),

    Move::new(chess::Square::B3, chess::Square::A1),
    Move::new(chess::Square::B3, chess::Square::A2),
    Move::new(chess::Square::B3, chess::Square::A4),
    Move::new(chess::Square::B3, chess::Square::A5),
    Move::new(chess::Square::B3, chess::Square::A6),
    Move::new(chess::Square::B3, chess::Square::A7),
    Move::new(chess::Square::B3, chess::Square::A8),
    Move::new(chess::Square::B3, chess::Square::B3),
    Move::new(chess::Square::B3, chess::Square::C3),
    Move::new(chess::Square::B3, chess::Square::D3),
    Move::new(chess::Square::B3, chess::Square::E3),
    Move::new(chess::Square::B3, chess::Square::F3),
    Move::new(chess::Square::B3, chess::Square::G3),
    Move::new(chess::Square::B3, chess::Square::H3),

    Move::new(chess::Square::B4, chess::Square::A1),
    Move::new(chess::Square::B4, chess::Square::A2),
    Move::new(chess::Square::B4, chess::Square::A3),
    Move::new(chess::Square::B4, chess::Square::A5),
    Move::new(chess::Square::B4, chess::Square::A6),
    Move::new(chess::Square::B4, chess::Square::A7),
    Move::new(chess::Square::B4, chess::Square::A8),
    Move::new(chess::Square::B4, chess::Square::B4),
    Move::new(chess::Square::B4, chess::Square::C4),
    Move::new(chess::Square::B4, chess::Square::D4),
    Move::new(chess::Square::B4, chess::Square::E4),
    Move::new(chess::Square::B4, chess::Square::F4),
    Move::new(chess::Square::B4, chess::Square::G4),
    Move::new(chess::Square::B4, chess::Square::H4),

    Move::new(chess::Square::B5, chess::Square::A1),
    Move::new(chess::Square::B5, chess::Square::A2),
    Move::new(chess::Square::B5, chess::Square::A3),
    Move::new(chess::Square::B5, chess::Square::A4),
    Move::new(chess::Square::B5, chess::Square::A6),
    Move::new(chess::Square::B5, chess::Square::A7),
    Move::new(chess::Square::B5, chess::Square::A8),
    Move::new(chess::Square::B5, chess::Square::B5),
    Move::new(chess::Square::B5, chess::Square::C5),
    Move::new(chess::Square::B5, chess::Square::D5),
    Move::new(chess::Square::B5, chess::Square::E5),
    Move::new(chess::Square::B5, chess::Square::F5),
    Move::new(chess::Square::B5, chess::Square::G5),
    Move::new(chess::Square::B5, chess::Square::H5),

    Move::new(chess::Square::B6, chess::Square::A1),
    Move::new(chess::Square::B6, chess::Square::A2),
    Move::new(chess::Square::B6, chess::Square::A3),
    Move::new(chess::Square::B6, chess::Square::A4),
    Move::new(chess::Square::B6, chess::Square::A5),
    Move::new(chess::Square::B6, chess::Square::A7),
    Move::new(chess::Square::B6, chess::Square::A8),
    Move::new(chess::Square::B6, chess::Square::B6),
    Move::new(chess::Square::B6, chess::Square::C6),
    Move::new(chess::Square::B6, chess::Square::D6),
    Move::new(chess::Square::B6, chess::Square::E6),
    Move::new(chess::Square::B6, chess::Square::F6),
    Move::new(chess::Square::B6, chess::Square::G6),
    Move::new(chess::Square::B6, chess::Square::H6),

    Move::new(chess::Square::B7, chess::Square::A1),
    Move::new(chess::Square::B7, chess::Square::A2),
    Move::new(chess::Square::B7, chess::Square::A3),
    Move::new(chess::Square::B7, chess::Square::A4),
    Move::new(chess::Square::B7, chess::Square::A5),
    Move::new(chess::Square::B7, chess::Square::A6),
    Move::new(chess::Square::B7, chess::Square::A8),
    Move::new(chess::Square::B7, chess::Square::B7),
    Move::new(chess::Square::B7, chess::Square::C7),
    Move::new(chess::Square::B7, chess::Square::D7),
    Move::new(chess::Square::B7, chess::Square::E7),

    Move::new(chess::Square::B8, chess::Square::A1),
    Move::new(chess::Square::B8, chess::Square::A2),
    Move::new(chess::Square::B8, chess::Square::A3),
    Move::new(chess::Square::B8, chess::Square::A4),
    Move::new(chess::Square::B8, chess::Square::A5),
    Move::new(chess::Square::B8, chess::Square::A6),
    Move::new(chess::Square::B8, chess::Square::A7),
    Move::new(chess::Square::B8, chess::Square::B8),
    Move::new(chess::Square::B8, chess::Square::C8),
    Move::new(chess::Square::B8, chess::Square::D8),
    Move::new(chess::Square::B8, chess::Square::E8),
    Move::new(chess::Square::B8, chess::Square::F8),
    Move::new(chess::Square::B8, chess::Square::G8),
    
    ///////////////////////////////////////////////
];
